/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


	void
calc_1(char *host)
{
	CLIENT *clnt;
	result  *result_1;
	data  output_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALC, ONE, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	output_1_arg.ws=0;

	while(1)
	{
		scanf("%s",output_1_arg.line);
		printf("Send: %s\n", output_1_arg.line);

		result_1 = output_1(&output_1_arg, clnt);

		if (result_1 == (result *) NULL)
		{
			clnt_perror (clnt, "call failed");
		}
		int i;

		if(result_1->log==1)
		{
			printf("Wynik: %d", result_1->res);
			break;
		}
		if(result_1->log == -1)
		{
			printf("Nie mozna dzielic przez 0");
			break;
		}
		for(i=0; i<result_1->ws; i++)
		{
			output_1_arg.stos[i]=result_1->stos[i];
		}
		output_1_arg.ws=result_1->ws;

	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


	int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calc_1 (host);
	exit (0);
}
