/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

	result *
output_1_svc(data *argp, struct svc_req *rqstp)
{
	static result  result;

	int  a, b, w, ws = argp->ws;
	result.log=0;
	w=0;

	printf("Zlapalem %s\n", argp->line);

	if(argp->line[0] >= '0' && argp->line[0] <= '9')
	{
		a = b = 0;
		do
		{
			a = 10 * a + argp->line[b++] - 48;
		}
		while(argp->line[b]);
		argp->stos[ws++] = a;
	}
	else if(argp->line[0] == '=')
	{
		result.res=argp->stos[--ws];
		result.log=1;
	}
	else
	{
		b = argp->stos[--ws];
		a = argp->stos[--ws];

		switch(argp->line[0])
		{
			case '+': w = a + b; break;
			case '-': w = a - b; break;
			case '*': w = a * b; break;
			case '/':
			if(b == 0)
			{
				result.log=-1;
			}
			else
			{w = a / b;}
			break;
			case '^': w = 1;
				  while(b--) w *= a;
				  break;
		}
		argp->stos[ws++] = w;
	}
	int i;
	for(i=0; i<ws; i++)
	{
		result.stos[i] = argp->stos[i];
	}
	result.ws = ws;

	return &result;
}
