/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data {
	char line[1024];
	int stos[256];
	int ws;
};
typedef struct data data;

struct result {
	int res;
	char log;
	char line[1024];
	int stos[256];
	int ws;
};
typedef struct result result;

#define CALC 0x20000006
#define ONE 1

#if defined(__STDC__) || defined(__cplusplus)
#define OUTPUT 1
extern  result * output_1(data *, CLIENT *);
extern  result * output_1_svc(data *, struct svc_req *);
extern int calc_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define OUTPUT 1
extern  result * output_1();
extern  result * output_1_svc();
extern int calc_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);
extern  bool_t xdr_result (XDR *, result*);

#else /* K&R C */
extern bool_t xdr_data ();
extern bool_t xdr_result ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
